using BF6CrashDiagnostic.Core.Sharing;
using BF6CrashDiagnostic.Core.Reporting;
using BF6CrashDiagnostic.Core.Models;

namespace BF6CrashDiagnostic.Tests;

public sealed class SafeSummaryServiceTests
{
    [Fact]
    public async Task ValidatedSchemaTwoArchive_ProducesTypedSafeSummary_WithoutRewritingSource()
    {
        using var directory = new TestDirectory();
        DiagnosticReportV3 seed = SafeSummaryTestData.Create();
        DateTimeOffset incidentTime = seed.StartUtc.AddMinutes(2);
        var legacy = new DiagnosticReport(
            2,
            "2.0.0-beta.1",
            "legacy-safe-summary-session",
            DiagnosticMode.Retrospective,
            seed.StartUtc,
            seed.EndUtc,
            SafeSummaryTestData.Canary,
            new CrashAnchor(
                incidentTime,
                "Microsoft-Windows-WER-SystemErrorReporting",
                1001,
                SafeSummaryTestData.Canary,
                "0x116",
                "C:\\Users\\Alice\\private.dmp"),
            seed.StartSnapshot,
            seed.EndSnapshot,
            [],
            seed.Events,
            seed.EventGroups,
            seed.Reliability,
            seed.Artifacts,
            seed.Findings,
            seed.CollectionStatus,
            SafeSummaryTestData.Canary + " summary");
        ReportPackage package = await new ReportWriter(directory.Path).WriteAsync(legacy);
        byte[] before = await File.ReadAllBytesAsync(package.ZipPath);
        var registry = new ReportHandleRegistry(directory.Path);
        UiReportHandle handle = await registry.RegisterValidatedAsync(ReportOrigin.Generated, [package.ZipPath]);
        var service = new SafeSummaryService();

        SafeSummaryPreview preview = await service.CreatePreviewAsync(handle, registry);

        Assert.Contains("Bugcheck 0x00000116 (VIDEO_TDR_FAILURE)", preview.Text, StringComparison.Ordinal);
        Assert.Contains("Generated by: PC Crash Diagnostic 3.2.0-beta.1", preview.Text, StringComparison.Ordinal);
        Assert.Contains("Source report version: 2.0.0-beta.1", preview.Text, StringComparison.Ordinal);
        Assert.Contains("Target executable: bf6.exe", preview.Text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(SafeSummaryTestData.Canary, preview.Text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("C:\\Users\\Alice", preview.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Equal(before, await File.ReadAllBytesAsync(package.ZipPath));
        Assert.Equal(preview.Text, await service.GetExactTextAsync(preview.PreviewToken));
    }

    [Fact]
    public async Task ExportAsync_WritesExactlyPreviewedText_AndDoesNotOverwrite()
    {
        using var directory = new TestDirectory();
        var service = new SafeSummaryService();
        SafeSummaryPreview preview = service.CreatePreview(SafeSummaryTestData.Create());
        string destination = Path.Combine(directory.Path, preview.SuggestedFileName);

        SafeSummaryExportResult result = await service.ExportAsync(preview.PreviewToken, destination);

        Assert.Equal(preview.Text, await File.ReadAllTextAsync(destination));
        Assert.Equal(new FileInfo(destination).Length, result.BytesWritten);
        Assert.False(result.Destination.IsSyncManaged);
        Assert.DoesNotContain(directory.Path, result.Destination.Warning, StringComparison.OrdinalIgnoreCase);
        await Assert.ThrowsAsync<IOException>(() => service.ExportAsync(preview.PreviewToken, destination));
    }

    [Fact]
    public async Task ExpiredPreview_CannotBeExported()
    {
        using var directory = new TestDirectory();
        var clock = new AdjustableTimeProvider(new DateTimeOffset(2026, 8, 16, 12, 0, 0, TimeSpan.Zero));
        var service = new SafeSummaryService(clock, TimeSpan.FromMinutes(1));
        SafeSummaryPreview preview = service.CreatePreview(SafeSummaryTestData.Create());
        clock.Advance(TimeSpan.FromMinutes(2));

        await Assert.ThrowsAsync<InvalidOperationException>(() => service.ExportAsync(
            preview.PreviewToken,
            Path.Combine(directory.Path, "summary.txt")));
    }

    [Fact]
    public async Task ExportAsync_RejectsDestinationDirectoryReplacementBeforeWritingAnyBytes()
    {
        using var directory = new TestDirectory();
        string exportDirectory = Path.Combine(directory.Path, "chosen-export-folder");
        string movedDirectory = Path.Combine(directory.Path, "original-export-folder");
        Directory.CreateDirectory(exportDirectory);
        var service = new SafeSummaryService(
            timeProvider: null,
            previewLifetime: null,
            beforeDestinationLeaseAcquisition: () =>
            {
                Directory.Move(exportDirectory, movedDirectory);
                Directory.CreateDirectory(exportDirectory);
            });
        SafeSummaryPreview preview = service.CreatePreview(SafeSummaryTestData.Create());
        string destination = Path.Combine(exportDirectory, "safe-summary.txt");

        await Assert.ThrowsAsync<IOException>(() => service.ExportAsync(preview.PreviewToken, destination));

        Assert.Empty(Directory.EnumerateFiles(exportDirectory));
        Assert.Empty(Directory.EnumerateFiles(movedDirectory));
        Assert.False(File.Exists(destination));
    }

    [Fact]
    public async Task HandleBoundPreview_RejectsReportReplacementAtExport()
    {
        using var directory = new TestDirectory();
        var writer = new ReportWriter(directory.Path);
        ReportPackageV3 package = await writer.WriteV3Async(SafeSummaryTestData.Create("bound-session"));
        var registry = new ReportHandleRegistry(directory.Path);
        UiReportHandle handle = await registry.RegisterValidatedAsync(ReportOrigin.Generated, [package.ZipPath]);
        var service = new SafeSummaryService();
        SafeSummaryPreview preview = await service.CreatePreviewAsync(handle, registry);
        Assert.Equal(preview.Text, await service.GetExactTextAsync(preview.PreviewToken));
        ReadOnlyMemory<byte> exactBytes = await service.GetExactUtf8Async(preview.PreviewToken);
        Assert.Equal(System.Text.Encoding.UTF8.GetBytes(preview.Text), exactBytes.ToArray());
        File.Delete(package.ZipPath);
        await File.WriteAllBytesAsync(package.ZipPath, [1, 2, 3, 4, 5]);

        await Assert.ThrowsAnyAsync<Exception>(() => service.ExportAsync(
            preview.PreviewToken,
            Path.Combine(directory.Path, "should-not-exist.txt")));
        await Assert.ThrowsAsync<InvalidOperationException>(() => service.GetExactTextAsync(preview.PreviewToken));
        Assert.False(File.Exists(Path.Combine(directory.Path, "should-not-exist.txt")));
    }

    [Fact]
    public async Task HandleBoundPreview_ReprojectsAndRejectsSameIdentityContentSubstitution()
    {
        using var targetData = new TestDirectory();
        using var replacementData = new TestDirectory();
        const string sessionId = "same-identity-summary-session";
        DiagnosticReportV3 original = SafeSummaryTestData.Create(sessionId);
        DiagnosticReportV3 changed = original with
        {
            Bugchecks =
            [
                original.Bugchecks[0] with
                {
                    Code = 0x117,
                    NormalizedCode = "0x00000117",
                    BugcheckName = "VIDEO_TDR_TIMEOUT_DETECTED"
                }
            ]
        };
        ReportPackageV3 target = await new ReportWriter(targetData.Path).WriteV3Async(original);
        ReportPackageV3 replacement = await new ReportWriter(replacementData.Path).WriteV3Async(changed);
        SafeSummaryTestData.SameIdentityArchiveSubstitution substitution =
            await SafeSummaryTestData.PrepareSameIdentitySubstitutionAsync(target.ZipPath, replacement.ZipPath);
        var registry = new ReportHandleRegistry(targetData.Path);
        UiReportHandle handle = await registry.RegisterValidatedAsync(ReportOrigin.Generated, [target.ZipPath]);
        var service = new SafeSummaryService();
        SafeSummaryPreview preview = await service.CreatePreviewAsync(handle, registry);

        await SafeSummaryTestData.ApplySameIdentitySubstitutionAsync(target.ZipPath, substitution);

        Assert.True(registry.IsValid(handle));
        InvalidDataException exception = await Assert.ThrowsAsync<InvalidDataException>(() =>
            service.GetExactTextAsync(preview.PreviewToken));
        Assert.Contains("content changed", exception.Message, StringComparison.OrdinalIgnoreCase);
        await Assert.ThrowsAsync<InvalidOperationException>(() =>
            service.GetExactTextAsync(preview.PreviewToken));
    }

    [Fact]
    public async Task RevokeForReport_InvalidatesAllBoundCopyTokens()
    {
        using var directory = new TestDirectory();
        var writer = new ReportWriter(directory.Path);
        ReportPackageV3 package = await writer.WriteV3Async(SafeSummaryTestData.Create("revoke-session"));
        var registry = new ReportHandleRegistry(directory.Path);
        UiReportHandle handle = await registry.RegisterValidatedAsync(ReportOrigin.Generated, [package.ZipPath]);
        var service = new SafeSummaryService();
        SafeSummaryPreview first = await service.CreatePreviewAsync(handle, registry);
        SafeSummaryPreview second = await service.CreatePreviewAsync(handle, registry);

        Assert.Equal(2, service.RevokeForReport(handle));
        await Assert.ThrowsAsync<InvalidOperationException>(() => service.GetExactTextAsync(first.PreviewToken));
        await Assert.ThrowsAsync<InvalidOperationException>(() => service.GetExactTextAsync(second.PreviewToken));
    }

    [Fact]
    public void DestinationClassifier_ReturnsFixedWarningsWithoutExposingPath()
    {
        using var directory = new TestDirectory();

        SafeExportDestinationAssessment synced = SafeExportDestinationClassifier.Classify(
            directory.Path,
            [directory.Path],
            DriveType.Fixed);
        SafeExportDestinationAssessment removable = SafeExportDestinationClassifier.Classify(
            directory.Path,
            [],
            DriveType.Removable);

        Assert.True(synced.IsSyncManaged);
        Assert.True(synced.RequiresPrivacyAcknowledgement);
        Assert.Contains("sync provider", synced.Warning, StringComparison.OrdinalIgnoreCase);
        Assert.Equal(SafeExportDestinationKind.Removable, removable.Kind);
        Assert.True(removable.RequiresPrivacyAcknowledgement);
        Assert.Contains("removable", removable.Warning, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(directory.Path, synced.Warning, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(directory.Path, removable.Warning, StringComparison.OrdinalIgnoreCase);
    }

    private sealed class AdjustableTimeProvider(DateTimeOffset now) : TimeProvider
    {
        private DateTimeOffset _now = now;
        public override DateTimeOffset GetUtcNow() => _now;
        public void Advance(TimeSpan value) => _now += value;
    }
}
