using System.Text;
using System.Reflection;
using System.Reflection.Emit;
using BF6CrashDiagnostic.Core.Models;
using BF6CrashDiagnostic.Core.Sharing;
using PCCrashDiagnostic.Contracts;

namespace BF6CrashDiagnostic.Tests;

public sealed class SafeSummaryPrivacyTests
{
    [Fact]
    public void SharingAssembly_DoesNotReferenceForbiddenFreeFormReportGetters()
    {
        var forbidden = new HashSet<(Type Type, string Getter)>
        {
            (typeof(DiagnosticEvent), "get_Message"),
            (typeof(DiagnosticEvent), "get_Data"),
            (typeof(DuplicateEventGroup), "get_Message"),
            (typeof(ReliabilityRecord), "get_Message"),
            (typeof(CollectionStatus), "get_Detail"),
            (typeof(DiagnosticReportV3), "get_Summary"),
            (typeof(DiagnosticFinding), "get_Title"),
            (typeof(DiagnosticFinding), "get_Evidence"),
            (typeof(DiagnosticFinding), "get_Meaning"),
            (typeof(DiagnosticFinding), "get_DoesNotProve"),
            (typeof(DiagnosticFinding), "get_NextCheck")
        };
        Assembly assembly = typeof(SafeSummaryProjector).Assembly;
        MethodInfo[] sharingMethods = assembly.GetTypes()
            .Where(type => type.Namespace == typeof(SafeSummaryProjector).Namespace)
            .SelectMany(type => type.GetMethods(
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance |
                BindingFlags.DeclaredOnly))
            .ToArray();

        var violations = new List<string>();
        foreach (MethodInfo method in sharingMethods)
        {
            foreach (MemberInfo member in ReadReferencedMembers(method))
            {
                if (member is MethodInfo referenced &&
                    referenced.DeclaringType is not null &&
                    forbidden.Contains((referenced.DeclaringType, referenced.Name)))
                {
                    violations.Add($"{method.DeclaringType?.FullName}.{method.Name} -> {referenced.DeclaringType.Name}.{referenced.Name}");
                }
            }
        }

        Assert.Empty(violations);
    }

    [Fact]
    public void ProjectAndRender_ExcludeFreeFormAndSensitiveFields()
    {
        SafeSummaryV1 summary = SafeSummaryProjector.Project(SafeSummaryTestData.Create());
        string text = SafeSummaryRenderer.Render(summary);
        byte[] bytes = SafeSummaryRenderer.RenderUtf8(summary);

        Assert.DoesNotContain(SafeSummaryTestData.Canary, text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("C:\\Users\\Alice", text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("safe-summary-session", text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(new string('a', 64), text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(new string('b', 64), text, StringComparison.OrdinalIgnoreCase);
        Assert.Equal(BuildProfile.Version, summary.GeneratorVersion);
        Assert.Equal(BuildProfile.Current.Profile, summary.GeneratorProfile);
        Assert.Equal(SafeSummaryTestData.Create().ToolVersion, summary.SourceReportVersion);
        Assert.Contains($"Generated by: PC Crash Diagnostic {BuildProfile.Version}", text, StringComparison.Ordinal);
        Assert.Contains($"Build profile: {BuildProfile.Current.Profile}", text, StringComparison.Ordinal);
        Assert.Contains("Bugcheck 0x00000116 (VIDEO_TDR_FAILURE)", text, StringComparison.Ordinal);
        Assert.Contains("WHEA event 18", text, StringComparison.Ordinal);
        Assert.Contains("WHEA event 18: Fatal, count 3.", text, StringComparison.Ordinal);
        Assert.Contains("Application crash marker", text, StringComparison.Ordinal);
        Assert.Contains("64.0 GiB", text, StringComparison.Ordinal);
        Assert.Contains("KB5030219", text, StringComparison.Ordinal);
        Assert.Contains("VIDEO_TDR_FAILURE_nvlddmkm!unknown_function", text, StringComparison.Ordinal);
        Assert.Contains("nvlddmkm.sys", text, StringComparison.Ordinal);
        Assert.Contains("Selected time (UTC): 2026-08-16 12:36Z", text, StringComparison.Ordinal);
        Assert.DoesNotContain("2026-08-16 12:34Z", text, StringComparison.Ordinal);
        Assert.DoesNotContain("2026-08-16 12:39Z", text, StringComparison.Ordinal);
        Assert.True(summary.ValuesWereOmitted);
        Assert.True(bytes.Length <= SafeSummaryRenderer.MaximumUtf8Bytes);
        Assert.False(bytes.AsSpan().StartsWith(Encoding.UTF8.Preamble));
        Assert.Equal(text, SafeSummaryRenderer.Render(SafeSummaryProjector.Project(SafeSummaryTestData.Create())));
    }

    [Fact]
    public void DebuggerProjection_MapsTaintedFieldsWithoutCopyingThem()
    {
        var report = SafeSummaryTestData.Create();
        report = report with
        {
            DebuggerAnalysis = report.DebuggerAnalysis! with
            {
                FailureBucket = "AV_C:\\Users\\Alice\\secret",
                ModuleName = "C:\\Users\\Alice\\evil.sys",
                ImageName = "alice@example.com",
                ProcessName = "C:\\Users\\Alice\\private.exe",
                SymbolStatus = "loaded alice@example.com",
                StackModules = ["C:\\Users\\Alice\\stack.sys", "alice@example.com"]
            }
        };

        string text = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(report));

        Assert.DoesNotContain("Alice", text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("alice@example.com", text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("AV_C:", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("evil.sys", text, StringComparison.Ordinal);
        Assert.Contains("private.exe", text, StringComparison.Ordinal);
        Assert.Contains("stack.sys", text, StringComparison.Ordinal);
        Assert.Contains("Symbol state: Unknown", text, StringComparison.Ordinal);
    }

    [Fact]
    public void StorageProjection_UsesSharedIntelRstCatalog_WithoutCopyingEventText()
    {
        var report = SafeSummaryTestData.Create();
        DateTimeOffset time = report.StartUtc.AddMinutes(1);
        report = report with
        {
            Events =
            [
                .. report.Events,
                new DiagnosticEvent(
                    time,
                    "System",
                    "iaStorAC",
                    null,
                    129,
                    2,
                    SafeSummaryTestData.Canary,
                    SafeSummaryTestData.Canary + " C:\\Users\\Alice",
                    new Dictionary<string, string> { [SafeSummaryTestData.Canary] = "private" }),
                new DiagnosticEvent(
                    time.AddSeconds(1),
                    "System",
                    "iaStorVD",
                    null,
                    129,
                    2,
                    SafeSummaryTestData.Canary,
                    SafeSummaryTestData.Canary + " controller text",
                    new Dictionary<string, string>())
            ]
        };

        string text = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(report));

        Assert.Contains("Storage error marker (event 129), count 2.", text, StringComparison.Ordinal);
        Assert.DoesNotContain(SafeSummaryTestData.Canary, text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("C:\\Users\\Alice", text, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void RecentChangeProjection_AllowsOnlyTypedKbAndOemInfReferences()
    {
        var report = SafeSummaryTestData.Create() with
        {
            RecentChanges = new RecentChangeTimeline(
                DateTimeOffset.UtcNow,
                DateTimeOffset.UtcNow.AddDays(-7),
                DateTimeOffset.UtcNow,
                [
                    new RecentSystemChange(DateTimeOffset.UtcNow, RecentChangeKind.DriverInstallation,
                        "Driver PRIVATE-CANARY.inf installed", "C:\\Users\\Alice\\PRIVATE-CANARY.inf", "Success", string.Empty),
                    new RecentSystemChange(DateTimeOffset.UtcNow, RecentChangeKind.DriverInstallation,
                        "Driver package oem42.inf installed", "Install", "Success", string.Empty),
                    new RecentSystemChange(DateTimeOffset.UtcNow, RecentChangeKind.WindowsUpdate,
                        "Update KB5030219", "Install", "Success", string.Empty)
                ],
                [])
        };

        string text = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(report));

        Assert.Contains("oem42.inf", text, StringComparison.Ordinal);
        Assert.Contains("KB5030219", text, StringComparison.Ordinal);
        Assert.DoesNotContain("PRIVATE-CANARY", text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("C:\\Users\\Alice", text, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void BugcheckProjection_UsesOfflineCatalog_AndIgnoresReportSuppliedName()
    {
        var known = SafeSummaryTestData.Create();
        known = known with
        {
            Bugchecks = [known.Bugchecks[0] with { BugcheckName = SafeSummaryTestData.Canary }]
        };
        var unknown = known with
        {
            Bugchecks =
            [
                known.Bugchecks[0] with
                {
                    Code = 0xDEAD,
                    NormalizedCode = "0x0000DEAD",
                    BugcheckName = SafeSummaryTestData.Canary
                }
            ]
        };

        string knownText = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(known));
        string unknownText = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(unknown));

        Assert.Contains("0x00000116 (VIDEO_TDR_FAILURE)", knownText, StringComparison.Ordinal);
        Assert.Contains("0x0000DEAD; parameters:", unknownText, StringComparison.Ordinal);
        Assert.DoesNotContain("0x0000DEAD (", unknownText, StringComparison.Ordinal);
        Assert.DoesNotContain(SafeSummaryTestData.Canary, knownText, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(SafeSummaryTestData.Canary, unknownText, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void DriverProjection_UsesCanonicalTypedFields_AndRejectsTaintedLabels()
    {
        var report = SafeSummaryTestData.Create();
        DateTimeOffset date = new(2026, 8, 15, 12, 34, 56, TimeSpan.Zero);
        report = report with
        {
            DriverInventory = new DriverInventory(
                date,
                [
                    new DriverDeviceRecord(
                        "DISPLAY",
                        "C:\\Users\\Alice\\private device",
                        SafeSummaryTestData.Canary,
                        "NVIDIA Corporation",
                        "32.0.15.6081",
                        date,
                        "C:\\Windows\\INF\\oem42.inf",
                        true,
                        SafeSummaryTestData.Canary,
                        0,
                        SafeSummaryTestData.Canary),
                    new DriverDeviceRecord(
                        SafeSummaryTestData.Canary,
                        SafeSummaryTestData.Canary,
                        SafeSummaryTestData.Canary,
                        "Microsoft " + SafeSummaryTestData.Canary,
                        "10.0." + SafeSummaryTestData.Canary,
                        date,
                        SafeSummaryTestData.Canary + ".inf",
                        false,
                        SafeSummaryTestData.Canary,
                        999,
                        SafeSummaryTestData.Canary)
                ],
                [])
        };

        SafeSummaryV1 projection = SafeSummaryProjector.Project(report);
        string text = SafeSummaryRenderer.Render(projection);

        SafeDriverFact fact = Assert.Single(projection.Drivers);
        Assert.Equal(SafeDriverProvider.Nvidia, fact.Provider);
        Assert.Equal(SafeDriverDeviceClass.Display, fact.DeviceClass);
        Assert.Contains(
            "Display; provider NVIDIA; version 32.0.15.6081; date 2026-08-15; signed yes; problem code 0; INF oem42.inf.",
            text,
            StringComparison.Ordinal);
        Assert.DoesNotContain("private device", text, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(SafeSummaryTestData.Canary, text, StringComparison.OrdinalIgnoreCase);
        Assert.True(projection.ValuesWereOmitted);
    }

    [Fact]
    public void WheaProjection_UsesTypedClassificationCategoryAndCount()
    {
        var report = SafeSummaryTestData.Create() with
        {
            WheaEvidence =
            [
                new WheaEvidence(18, BF6CrashDiagnostic.Core.Analysis.WheaEventClassification.Fatal, WheaEvidenceCategory.Memory, 2),
                new WheaEvidence(19, BF6CrashDiagnostic.Core.Analysis.WheaEventClassification.Corrected, WheaEvidenceCategory.PCIe, 3)
            ]
        };

        string text = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(report));

        Assert.Contains("WHEA event 18: Fatal, Memory, count 2.", text, StringComparison.Ordinal);
        Assert.Contains("WHEA event 19: Corrected, PCIe, count 3.", text, StringComparison.Ordinal);
        Assert.DoesNotContain(SafeSummaryTestData.Canary, text, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Project_RejectsNonSchemaThreeReport()
    {
        var report = SafeSummaryTestData.Create() with { ReportSchemaVersion = 2 };

        Assert.Throws<InvalidDataException>(() => SafeSummaryProjector.Project(report));
    }

    [Fact]
    public void MotherboardAndBios_AreIncludedOnlyAfterTypedSanitization()
    {
        var report = SafeSummaryTestData.Create();
        report = report with
        {
            EndSnapshot = report.EndSnapshot! with
            {
                MotherboardManufacturer = "Gigabyte Technology Co., Ltd.",
                MotherboardProduct = "X870 AORUS ELITE WIFI7 ICE",
                BiosVersion = "F8"
            }
        };

        string text = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(report));

        Assert.Contains("Motherboard: Gigabyte; X870 AORUS ELITE WIFI7 ICE", text, StringComparison.Ordinal);
        Assert.Contains("BIOS version: F8", text, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("X870 PRIVATE-CANARY@example.com")]
    [InlineData("X870 C:\\Users\\PRIVATE-CANARY")]
    [InlineData("X870 PRIVATE-CANARY\r\nICE")]
    [InlineData("X870 192.168.1.5 PRIVATE-CANARY")]
    [InlineData("X870 00:11:22:33:44:55 PRIVATE-CANARY")]
    [InlineData("X870 8444a4fb-d8d3-4f38-84f8-89960a1ef12f PRIVATE-CANARY")]
    [InlineData("X870 ‮PRIVATE-CANARY")]
    public void MotherboardProduct_TaintCorpusIsOmitted(string product)
    {
        var report = SafeSummaryTestData.Create();
        report = report with
        {
            EndSnapshot = report.EndSnapshot! with
            {
                MotherboardManufacturer = "Gigabyte Technology Co., Ltd.",
                MotherboardProduct = product,
                BiosVersion = "F8\r\nPRIVATE-CANARY"
            }
        };

        string text = SafeSummaryRenderer.Render(SafeSummaryProjector.Project(report));

        Assert.DoesNotContain("PRIVATE-CANARY", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Motherboard: Gigabyte", text, StringComparison.Ordinal);
        Assert.Contains("BIOS version: not available", text, StringComparison.Ordinal);
    }

    private static IEnumerable<MemberInfo> ReadReferencedMembers(MethodBase method)
    {
        byte[]? il = method.GetMethodBody()?.GetILAsByteArray();
        if (il is null)
        {
            yield break;
        }

        int offset = 0;
        while (offset < il.Length)
        {
            ushort value = il[offset++];
            if (value == 0xFE)
            {
                value = (ushort)(0xFE00 | il[offset++]);
            }

            if (!OpCodesByValue.TryGetValue(value, out OpCode opcode))
            {
                throw new InvalidDataException($"Unknown IL opcode 0x{value:X4} in {method.Name}.");
            }

            int operandOffset = offset;
            int operandSize = OperandSize(opcode.OperandType, il, operandOffset);
            if (opcode.OperandType is OperandType.InlineField or OperandType.InlineMethod or OperandType.InlineTok)
            {
                int token = BitConverter.ToInt32(il, operandOffset);
                MemberInfo? member = null;
                try
                {
                    member = method.Module.ResolveMember(
                        token,
                        method.DeclaringType?.GetGenericArguments(),
                        method.IsGenericMethod ? method.GetGenericArguments() : null);
                }
                catch (ArgumentException)
                {
                    // An unresolved generic token cannot name one of the concrete model getters above.
                }

                if (member is not null)
                {
                    yield return member;
                }
            }

            offset += operandSize;
        }
    }

    private static int OperandSize(OperandType operandType, byte[] il, int offset) => operandType switch
    {
        OperandType.InlineNone => 0,
        OperandType.ShortInlineBrTarget or OperandType.ShortInlineI or OperandType.ShortInlineVar => 1,
        OperandType.InlineVar => 2,
        OperandType.InlineBrTarget or OperandType.InlineField or OperandType.InlineI or
            OperandType.InlineMethod or OperandType.InlineSig or OperandType.InlineString or
            OperandType.InlineTok or OperandType.InlineType or OperandType.ShortInlineR => 4,
        OperandType.InlineI8 or OperandType.InlineR => 8,
        OperandType.InlineSwitch => 4 + checked(BitConverter.ToInt32(il, offset) * 4),
        _ => throw new InvalidDataException($"Unsupported IL operand type {operandType}.")
    };

    private static readonly IReadOnlyDictionary<ushort, OpCode> OpCodesByValue = typeof(OpCodes)
        .GetFields(BindingFlags.Public | BindingFlags.Static)
        .Where(field => field.FieldType == typeof(OpCode))
        .Select(field => (OpCode)field.GetValue(null)!)
        .ToDictionary(opcode => unchecked((ushort)opcode.Value));
}
