using System.Globalization;
using System.Text;
using BF6CrashDiagnostic.Core.Models;

namespace BF6CrashDiagnostic.Core.Sharing;

public static class SafeSummaryRenderer
{
    public const int MaximumUtf8Bytes = 256 * 1024;

    public static byte[] RenderUtf8(SafeSummaryV1 summary)
    {
        ArgumentNullException.ThrowIfNull(summary);
        if (summary.FormatVersion != 1)
        {
            throw new InvalidDataException("Only Safe Summary format 1 can be rendered.");
        }

        string text = Render(summary);
        byte[] bytes = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true).GetBytes(text);
        if (bytes.Length > MaximumUtf8Bytes)
        {
            throw new InvalidDataException("The Safe Summary exceeds the 256 KiB export limit.");
        }

        return bytes;
    }

    public static string Render(SafeSummaryV1 summary)
    {
        ArgumentNullException.ThrowIfNull(summary);
        var builder = new StringBuilder(16 * 1024);
        Line(builder, "PC Crash Diagnostic - Safe Support Summary");
        Line(builder, "Format: 1");
        Line(builder, "Generated by: PC Crash Diagnostic " + summary.GeneratorVersion);
        Line(builder, "Build profile: " + summary.GeneratorProfile);
        Line(builder, "Source report version: " + summary.SourceReportVersion);
        Line(builder, "Privacy: no event messages, paths, identifiers, dump bytes, or debugger logs");
        Line(builder);

        Heading(builder, "Incident");
        Field(builder, "Selected type", Human(summary.IncidentKind));
        Field(builder, "Selected time (UTC)", summary.IncidentTimeUtc.HasValue ? Time(summary.IncidentTimeUtc.Value) : "not available");
        Field(builder, "Target executable", summary.TargetExecutable ?? "not selected");

        if (summary.System is not null)
        {
            Heading(builder, "System");
            Field(builder, "CPU", summary.System.CpuName ?? "not available");
            Field(builder, "GPU", summary.System.GpuNames.Count == 0 ? "not available" : string.Join(", ", summary.System.GpuNames));
            Field(builder, "Installed memory", FormatBytes(summary.System.TotalPhysicalMemoryBytes));
            if (summary.System.MotherboardVendor != SafeMotherboardVendor.Unknown)
            {
                Field(builder, "Motherboard", JoinAvailable(MotherboardVendorLabel(summary.System.MotherboardVendor), summary.System.MotherboardProduct));
                Field(builder, "BIOS version", summary.System.BiosVersion ?? "not available");
            }
            Field(builder, "Windows", JoinAvailable(summary.System.WindowsCaption, summary.System.WindowsVersion, "build " + summary.System.WindowsBuild, summary.System.WindowsArchitecture));
            Field(builder, "Preview build detected", YesNo(summary.System.PreviewBuildDetected));
        }

        Heading(builder, "Crash evidence");
        if (summary.Bugchecks.Count == 0)
        {
            Line(builder, "- No normalized bugcheck record was included.");
        }
        else
        {
            foreach (SafeBugcheck item in summary.Bugchecks)
            {
                string parameters = string.Join(", ", item.Parameters.Select(value => value.HasValue ? $"0x{value.Value:X}" : "unknown"));
                string catalogName = item.CatalogName is null ? string.Empty : $" ({item.CatalogName})";
                Line(builder, $"- Bugcheck 0x{item.Code:X8}{catalogName}; parameters: {parameters}; source: {Human(item.EvidenceSource)}.");
            }
        }

        foreach (SafeWheaSignal item in summary.WheaSignals)
        {
            string category = item.Category.HasValue ? $", {WheaCategoryLabel(item.Category.Value)}" : string.Empty;
            Line(builder, $"- WHEA event {item.EventId}: {Human(item.Classification)}{category}, count {item.Count.ToString(CultureInfo.InvariantCulture)}.");
        }

        foreach (SafeEvidenceSignal item in summary.EvidenceSignals)
        {
            Line(builder, $"- {EvidenceLabel(item.Kind)} (event {item.EventId}), count {item.Count.ToString(CultureInfo.InvariantCulture)}.");
        }

        if (summary.CrashReadiness is not null)
        {
            SafeReadinessFacts item = summary.CrashReadiness;
            Heading(builder, "Crash capture readiness");
            Field(builder, "Assessment", Human(item.Assessment));
            Field(builder, "Dump mode", Human(item.DumpMode));
            Field(builder, "Activation", Human(item.ActivationState));
            Field(builder, "Crash-event logging", YesNoUnknown(item.EventLoggingEnabled));
            Field(builder, "Overwrite enabled", YesNoUnknown(item.OverwriteEnabled));
            Field(builder, "System-managed page file", YesNoUnknown(item.SystemManagedPageFile));
            Field(builder, "Dump destination accessible", YesNoUnknown(item.DumpDestinationAccessible));
            Field(builder, "Required backing", SizeBucket(item.RequiredBacking));
            Field(builder, "Destination free space", SizeBucket(item.AvailableDestinationSpace));
        }

        Heading(builder, "Dump metadata");
        if (summary.Dumps.Count == 0)
        {
            Line(builder, "- No dump candidate metadata was included.");
        }
        else
        {
            foreach (SafeDumpFact item in summary.Dumps)
            {
                Line(builder, $"- {Human(item.Kind)}; {Human(item.Format)}; {Human(item.InspectionState)}; size {SizeBucket(item.Size)}.");
            }
        }

        if (summary.DumpQuality is not null)
        {
            SafeDumpQualityFact item = summary.DumpQuality;
            Field(builder, "Dump quality", $"{Human(item.Classification)}; {Human(item.Format)}; DumpChk {Human(item.DumpChkState)}");
        }

        if (summary.Storage.Count > 0)
        {
            Heading(builder, "Storage health");
            foreach (SafeStorageFact item in summary.Storage)
            {
                string optional = string.Join(", ", new[]
                {
                    item.TemperatureCelsius.HasValue ? item.TemperatureCelsius.Value.ToString(CultureInfo.InvariantCulture) + " C" : null,
                    item.WearPercent.HasValue ? item.WearPercent.Value.ToString(CultureInfo.InvariantCulture) + "% wear" : null,
                    item.HasReportedErrors ? "reported errors present" : "no reported error counters",
                    item.HasReportedHighLatency ? "high latency counter present" : "no high latency counter"
                }.Where(value => value is not null));
                Line(builder, $"- Disk {item.Ordinal.ToString(CultureInfo.InvariantCulture)}: {StorageMediaLabel(item.MediaType)}, {StorageBusLabel(item.BusType)}, {Human(item.Health)}; {optional}.");
            }
        }

        if (summary.RecentChanges.Count > 0)
        {
            Heading(builder, "Recent changes (timing context only)");
            foreach (SafeRecentChangeFact item in summary.RecentChanges)
            {
                string proximity = item.Within24Hours ? "within 24 hours" : item.WithinSevenDays ? "within 7 days" : "outside 7 days";
                Line(builder, $"- {Human(item.Kind)}{(item.Reference is null ? string.Empty : " " + item.Reference)}: {Human(item.Result)}, {proximity}.");
            }
        }

        if (summary.DriverVerifier is not null)
        {
            SafeDriverVerifierFact item = summary.DriverVerifier;
            Heading(builder, "Driver Verifier");
            Field(builder, "State", Human(item.Status));
            Field(builder, "Flags", item.Flags.HasValue ? $"0x{item.Flags.Value:X8}" : "not available");
            Field(builder, "Verified drivers", item.VerifiedDriverBasenames.Count == 0 ? "none listed" : string.Join(", ", item.VerifiedDriverBasenames));
            if (item.OmittedDriverCount > 0)
            {
                Field(builder, "Additional driver names omitted", item.OmittedDriverCount.ToString(CultureInfo.InvariantCulture));
            }
        }

        if (summary.Drivers.Count > 0)
        {
            Heading(builder, "Relevant driver context");
            foreach (SafeDriverFact item in summary.Drivers)
            {
                string date = item.DriverDateUtc?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? "not available";
                string signed = item.IsSigned switch { true => "yes", false => "no", _ => "unknown" };
                string problem = item.DeviceManagerProblemCode?.ToString(CultureInfo.InvariantCulture) ?? "unknown";
                Line(builder,
                    $"- {DriverClassLabel(item.DeviceClass)}; provider {DriverProviderLabel(item.Provider)}; " +
                    $"version {item.Version ?? "not available"}; date {date}; signed {signed}; " +
                    $"problem code {problem}; INF {item.InfBasename ?? "not available"}.");
            }
        }

        if (summary.Debugger is not null)
        {
            SafeDebuggerFact item = summary.Debugger;
            Heading(builder, "WinDbg-reported fields");
            Field(builder, "Analysis state", Human(item.State));
            Field(builder, "Symbol access", Human(item.SymbolAccess));
            Field(builder, "Symbol state", Human(item.SymbolStatus));
            Field(builder, "Failure bucket", item.FailureBucket ?? "not available");
            Field(builder, "Named module", item.ModuleBasename ?? "not available");
            Field(builder, "Image", item.ImageBasename ?? "not available");
            Field(builder, "Process", item.ProcessBasename ?? "not available");
            Field(builder, "Stack modules", item.StackModuleBasenames.Count == 0 ? "none included" : string.Join(", ", item.StackModuleBasenames));
            if (item.OmittedStackModuleCount > 0)
            {
                Field(builder, "Additional stack modules omitted", item.OmittedStackModuleCount.ToString(CultureInfo.InvariantCulture));
            }
            Line(builder, "- These values were reported by WinDbg and do not confirm a faulty driver or process.");
        }

        Heading(builder, "Source coverage");
        if (summary.Coverage.Count == 0)
        {
            Line(builder, "- No recognized source-coverage records were included.");
        }
        else
        {
            foreach (SafeCoverageFact item in summary.Coverage)
            {
                Line(builder, $"- {CoverageLabel(item.Source)}: {Human(item.State)}, {item.RecordCount.ToString(CultureInfo.InvariantCulture)} record(s).");
            }
        }

        Heading(builder, "Observed finding categories");
        if (summary.Findings.Count == 0)
        {
            Line(builder, "- No allowlisted finding category was included.");
        }
        else
        {
            foreach (SafeFindingKind item in summary.Findings)
            {
                Line(builder, "- " + FindingLabel(item));
            }
        }

        Heading(builder, "Limits");
        Line(builder, "- This summary reports Windows evidence and does not identify a component as defective.");
        Line(builder, "- Timing and recurrence can guide the next check but do not establish causation.");
        Line(builder, "- No cause was identified in the Windows records this app could read.");
        if (summary.ValuesWereOmitted)
        {
            Line(builder, "- Unrecognized, unsafe, or over-limit values were omitted.");
        }

        return builder.ToString();
    }

    private static void Heading(StringBuilder builder, string value)
    {
        Line(builder);
        Line(builder, value);
        Line(builder, new string('-', value.Length));
    }

    private static void Field(StringBuilder builder, string label, string value) => Line(builder, $"{label}: {value}");
    private static void Line(StringBuilder builder, string value = "") => builder.Append(value).Append("\r\n");
    private static string Time(DateTimeOffset value) => value.ToUniversalTime().ToString("yyyy-MM-dd HH:mm'Z'", CultureInfo.InvariantCulture);
    private static string YesNo(bool value) => value ? "yes" : "no";
    private static string YesNoUnknown(bool? value) => value.HasValue ? YesNo(value.Value) : "not available";
    private static string Human<T>(T value) where T : struct, Enum => SplitWords(value.ToString());

    private static string SplitWords(string value)
    {
        var builder = new StringBuilder(value.Length + 8);
        for (int index = 0; index < value.Length; index++)
        {
            char character = value[index];
            if (index > 0 && char.IsUpper(character) && !char.IsUpper(value[index - 1]))
            {
                builder.Append(' ');
            }

            builder.Append(character);
        }

        return builder.ToString();
    }

    private static string JoinAvailable(params string?[] values)
    {
        string[] present = values
            .Where(value => !string.IsNullOrWhiteSpace(value) && !value.EndsWith(' '))
            .Cast<string>()
            .ToArray();
        return present.Length == 0 ? "not available" : string.Join("; ", present);
    }

    private static string FormatBytes(ulong? bytes)
    {
        if (!bytes.HasValue)
        {
            return "not available";
        }

        double gib = bytes.Value / (1024d * 1024d * 1024d);
        return gib.ToString("0.0", CultureInfo.InvariantCulture) + " GiB";
    }

    private static string SizeBucket(SafeSizeBucket value) => value switch
    {
        SafeSizeBucket.Unknown => "not available",
        SafeSizeBucket.Empty => "empty",
        SafeSizeBucket.UnderOneMiB => "under 1 MiB",
        SafeSizeBucket.OneToSixteenMiB => "1-16 MiB",
        SafeSizeBucket.SixteenToTwoHundredFiftySixMiB => "16-256 MiB",
        SafeSizeBucket.TwoHundredFiftySixMiBToOneGiB => "256 MiB-1 GiB",
        SafeSizeBucket.OneToEightGiB => "1-8 GiB",
        SafeSizeBucket.EightToThirtyTwoGiB => "8-32 GiB",
        SafeSizeBucket.OverThirtyTwoGiB => "over 32 GiB",
        _ => "not available"
    };

    private static string EvidenceLabel(SafeEvidenceSignalKind value) => value switch
    {
        SafeEvidenceSignalKind.BugcheckReport => "Windows bugcheck report",
        SafeEvidenceSignalKind.UnexpectedPowerLoss => "Unexpected power-loss/restart marker",
        SafeEvidenceSignalKind.UnexpectedShutdown => "Unexpected shutdown marker",
        SafeEvidenceSignalKind.DumpWriteFailure => "Crash-dump write failure marker",
        SafeEvidenceSignalKind.GpuReset => "Display-driver reset marker",
        SafeEvidenceSignalKind.StorageError => "Storage error marker",
        SafeEvidenceSignalKind.FileSystemError => "File-system error marker",
        SafeEvidenceSignalKind.MemoryDiagnostic => "Windows Memory Diagnostic result",
        SafeEvidenceSignalKind.ApplicationCrash => "Application crash marker",
        SafeEvidenceSignalKind.ApplicationHang => "Application hang marker",
        SafeEvidenceSignalKind.ResourceExhaustion => "Resource exhaustion marker",
        _ => "Recognized Windows evidence"
    };

    private static string DriverProviderLabel(SafeDriverProvider value) => value switch
    {
        SafeDriverProvider.Microsoft => "Microsoft",
        SafeDriverProvider.Nvidia => "NVIDIA",
        SafeDriverProvider.Amd => "AMD",
        SafeDriverProvider.Intel => "Intel",
        SafeDriverProvider.Realtek => "Realtek",
        SafeDriverProvider.Broadcom => "Broadcom",
        SafeDriverProvider.Qualcomm => "Qualcomm",
        SafeDriverProvider.Marvell => "Marvell",
        SafeDriverProvider.MediaTek => "MediaTek",
        SafeDriverProvider.Logitech => "Logitech",
        SafeDriverProvider.Corsair => "Corsair",
        SafeDriverProvider.SteelSeries => "SteelSeries",
        SafeDriverProvider.Asus => "ASUS",
        SafeDriverProvider.Gigabyte => "Gigabyte",
        SafeDriverProvider.Msi => "MSI",
        _ => "Unknown"
    };

    private static string DriverClassLabel(SafeDriverDeviceClass value) => value switch
    {
        SafeDriverDeviceClass.Display => "Display",
        SafeDriverDeviceClass.Hdc => "Storage controller",
        SafeDriverDeviceClass.ScsiAdapter => "SCSI adapter",
        SafeDriverDeviceClass.Net => "Network",
        SafeDriverDeviceClass.Media => "Media",
        SafeDriverDeviceClass.System => "System",
        SafeDriverDeviceClass.Processor => "Processor",
        SafeDriverDeviceClass.Memory => "Memory",
        SafeDriverDeviceClass.Usb => "USB",
        SafeDriverDeviceClass.Bluetooth => "Bluetooth",
        _ => "Unknown"
    };

    private static string WheaCategoryLabel(WheaEvidenceCategory value) => value switch
    {
        WheaEvidenceCategory.Processor => "Processor",
        WheaEvidenceCategory.Memory => "Memory",
        WheaEvidenceCategory.PCIe => "PCIe",
        WheaEvidenceCategory.Generic => "Generic hardware",
        _ => "Unknown"
    };

    private static string StorageMediaLabel(SafeStorageMediaType value) => value switch
    {
        SafeStorageMediaType.Hdd => "HDD",
        SafeStorageMediaType.Ssd => "SSD",
        SafeStorageMediaType.Scm => "storage-class memory",
        _ => "unknown media"
    };

    private static string StorageBusLabel(SafeStorageBusType value) => value switch
    {
        SafeStorageBusType.Ata => "ATA",
        SafeStorageBusType.Sata => "SATA",
        SafeStorageBusType.Sas => "SAS",
        SafeStorageBusType.Nvme => "NVMe",
        SafeStorageBusType.Usb => "USB",
        SafeStorageBusType.Sd => "SD",
        SafeStorageBusType.Mmc => "MMC",
        SafeStorageBusType.Raid => "RAID",
        SafeStorageBusType.StorageSpaces => "Storage Spaces",
        SafeStorageBusType.Virtual => "virtual",
        _ => "unknown bus"
    };

    private static string MotherboardVendorLabel(SafeMotherboardVendor value) => value switch
    {
        SafeMotherboardVendor.Asus => "ASUS",
        SafeMotherboardVendor.Gigabyte => "Gigabyte",
        SafeMotherboardVendor.Msi => "MSI",
        SafeMotherboardVendor.Asrock => "ASRock",
        SafeMotherboardVendor.Dell => "Dell",
        SafeMotherboardVendor.Hp => "HP",
        SafeMotherboardVendor.Lenovo => "Lenovo",
        SafeMotherboardVendor.Acer => "Acer",
        SafeMotherboardVendor.Microsoft => "Microsoft",
        SafeMotherboardVendor.Framework => "Framework",
        SafeMotherboardVendor.Supermicro => "Supermicro",
        _ => "unknown vendor"
    };

    private static string CoverageLabel(SafeCoverageSource value) => value switch
    {
        SafeCoverageSource.SystemEvents => "System event log",
        SafeCoverageSource.ApplicationEvents => "Application event log",
        SafeCoverageSource.KernelEventTracing => "Kernel event-tracing log",
        SafeCoverageSource.ReliabilityHistory => "Reliability history",
        SafeCoverageSource.CrashArtifacts => "Crash artifact inventory",
        SafeCoverageSource.CrashReadiness => "Crash-capture readiness",
        SafeCoverageSource.DumpInventory => "Dump inventory and quality",
        SafeCoverageSource.DriverInventory => "Driver and device inventory",
        SafeCoverageSource.WindowsUpdateHistory => "Windows Update history",
        SafeCoverageSource.DriverInstallHistory => "Driver-install history",
        SafeCoverageSource.StorageHealth => "Storage health",
        SafeCoverageSource.DriverVerifier => "Driver Verifier settings",
        SafeCoverageSource.SystemSnapshot => "System snapshot",
        _ => "Other recognized source"
    };

    private static string FindingLabel(SafeFindingKind value) => value switch
    {
        SafeFindingKind.Bugcheck => "A bugcheck record was observed.",
        SafeFindingKind.HardwareError => "A WHEA hardware-error record was observed.",
        SafeFindingKind.DumpWriteFailure => "Windows reported a crash-dump write problem.",
        SafeFindingKind.GpuTimeout => "A graphics reset or timeout marker was observed.",
        SafeFindingKind.ResourceExhaustion => "A resource-exhaustion marker was observed.",
        SafeFindingKind.RisingMemoryUse => "Memory use increased during the monitored interval.",
        SafeFindingKind.ApplicationFailure => "An application crash or hang marker was observed.",
        SafeFindingKind.UnexpectedShutdown => "An unexpected shutdown marker was observed.",
        SafeFindingKind.DumpQuality => "The selected dump has a bounded quality assessment.",
        SafeFindingKind.StorageHealthWarning => "Windows reported a storage-health warning.",
        SafeFindingKind.DriverVerifierEnabled => "Driver Verifier appears to be enabled.",
        SafeFindingKind.RecentSystemChanges => "Recent update or driver-install timing was observed.",
        _ => "A recognized diagnostic category was observed."
    };
}
