namespace BF6CrashDiagnostic.Core.Analysis;

/// <summary>
/// Identifies evidence generated by this diagnostic tool so its own name cannot be
/// mistaken for Battlefield 6 merely because it contains the token "BF6".
/// </summary>
public static class DiagnosticSignalClassifier
{
    public static bool IsDiagnosticToolSelfSignal(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return false;
        }

        return text.Contains("PCCrashDiagnost", StringComparison.OrdinalIgnoreCase) ||
               text.Contains("PC Crash Diagnostic", StringComparison.OrdinalIgnoreCase) ||
               text.Contains("BF6CrashDiagnost", StringComparison.OrdinalIgnoreCase) ||
               text.Contains("bf6-crash-diagnostic", StringComparison.OrdinalIgnoreCase) ||
               text.Contains("Unofficial BF6 Crash Diagnostic", StringComparison.OrdinalIgnoreCase);
    }
}
